name: Rust CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Stable with rustfmt and clippy
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - name: Annotate commit with clippy warnings - UDP
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --no-default-features --features use-udp
      - name: Annotate commit with clippy warnings - WebRTC
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --no-default-features --features use-webrtc
      - name: Security audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          default: true

      - name: Release build - UDP
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --no-default-features --features use-udp
          
      - name: Release build - WebRTC
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --no-default-features --features use-webrtc

      - name: Example 'server' - UDP
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --example server --no-default-features --features use-udp
      
      - name: Example 'client' - UDP
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --example client --no-default-features --features use-udp

      - name: Example 'server' - WebRTC
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --example server --no-default-features --features use-webrtc
      
      - name: Example 'client' - WASM
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --example client --target wasm32-unknown-unknown --no-default-features --features use-webrtc
